CREATE SCHEMA IF NOT EXISTS INDITEX_CORE_PLATFORM;

CREATE TABLE INDITEX_CORE_PLATFORM.PRICES (
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    PRIMARY KEY (PRODUCT_ID, BRAND_ID, START_DATE)
);