CREATE SCHEMA IF NOT EXISTS INDITEX_CORE_PLATFORM;

CREATE TABLE INDITEX_CORE_PLATFORM.product_prices (
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    PRIMARY KEY (PRODUCT_ID, BRAND_ID, START_DATE)
);